language: python

python:
  - "2.7"

install:
  - pip install cwlref-runner
  - pip install cwltool
  - pip install cwl-runner

script:
  # Validate schama-salad-tool
  - schema-salad-tool /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cwltool/schemas/v1.0/CommandLineTool-standalone.yml hello.cwl
  - schema-salad-tool /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cwltool/schemas/v1.0/CommandLineTool-standalone.yml grep.cwl
  - schema-salad-tool /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cwltool/schemas/v1.0/CommandLineTool-standalone.yml wc.cwl
  #- schema-salad-tool /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cwltool/schemas/v1.0/Workflow.yml grep-and-count.cwl
  # test result output
  - cwltool hello.cwl  --message "hello world" 
