language: python

python:
  - "2.7"

install:
  - pip install cwlref-runner
  - pip install cwltool
  - pip install cwl-runner

script:
  # Validate schama-salad-tool
  - schema-salad-tool /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cwltool/schemas/v1.0/CommonWorkflowLanguage.yml hello.cwl
  - schema-salad-tool /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cwltool/schemas/v1.0/CommonWorkflowLanguage.yml grep.cwl
  - schema-salad-tool /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cwltool/schemas/v1.0/CommonWorkflowLanguage.yml wc.cwl
  - schema-salad-tool /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cwltool/schemas/v1.0/CommonWorkflowLanguage.yml grep-and-count.cwl
  # test result output
  - cwltool hello.cwl  --message "hello world" ; grep "hello world fail" hello.-out.txt
