language: python

python:
  - "3.6"

install:
  - pip install cwlref-runner
  - pip install cwltool
  - pip install cwl-runner

script:
  # Validate schama-salad-tool
  # if error happens check python version at travis console.
  - cwltool --validate helloworld.cwl
  - cwltool --validate grep.cwl
  - cwltool --validate wc.cwl
  - cwltool --validate grep-and-count.cwl
  # test result output
  - cwltool helloworld.cwl  --message "Hello World" ; grep "Hello World" hello-out.txt
  # Workflow
  - cwltool grep-and-count.cwl --target_file mock.txt --grep_pattern one ;   awk '{print $1}' wcout.txt  | grep 2
  - cwltool grep-and-count.cwl --target_file mock2.txt --grep_pattern one ;   awk '{print $1}' wcout.txt  | grep 3
