language: python

python:
  - "2.7"

install:
  - pip install cwlref-runner
  - pip install cwltool
  - pip install cwl-runner

script:
  - schema-salad-tool /usr/local/lib/python2.7/dist-packages/cwltool/schemas/v1.0/CommandLineTool-standalone.yml hello.cwl
